using System;
using ElzUtilLibary.Database.Attributes;

namespace ElzUtilLibaryUnitTest.TestModel
{
    [Tablename(Name = "Person")]
    public class Person2
    {
        [PrimaryKey]
        [PrimaryKeyAutogeneratedByDatabase]
        public int PersId { get; set; }

        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public DateTime Birthday { get; set; }
    }
}