using System;

namespace ElzUtilLibary.Database.Attributes
{
    [AttributeUsage(AttributeTargets.Property,
        AllowMultiple = false)
    ]
    public class PrimaryKeyAutogeneratedByDatabase : Attribute
    {
        public PrimaryKeyAutogeneratedByDatabase()
        {
            IsAutogenerated = true;
        }

        public bool IsAutogenerated { get; set; }
    }
}