using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SQLite;
using System.Reflection;
using ElzUtilLibary.Database.Attributes;
using ElzUtilLibary.Mapping;
using MySql.Data.MySqlClient;

namespace ElzUtilLibary.Database
{
    public abstract class AbstractDatabaseConnector : IDatabaseConnector
    {
        public enum Database
        {
            MsSql,
            MySql,
            Sqlite,
        }

        private const string SqlInsertTemplate = "INSERT INTO {0} ({1}) VALUES ({2})";
        protected readonly string ConnectionString = string.Empty;
        protected Database DatabaseType;

        internal AbstractDatabaseConnector(Database database, string connectionString)
        {
            DatabaseType = database;
            ConnectionString = connectionString;
        }

        public List<T> GetData<T>(string sqlStatement) where T : new()
        {
            DataTable table = ReadData<T>(sqlStatement);

            return MappingHelper.MapDataTableToObjectList<T>(table);
        }

        public void InsertData(string sqlStatement)
        {
            using (IDbConnection connection = GetDbConnection())
            {
                connection.Open();

                using (IDbCommand command = GetDbCommand())
                {
                    command.Connection = connection;
                    command.CommandText = sqlStatement;

                    command.ExecuteNonQuery();

                    command.Dispose();
                }

                connection.Close();
                connection.Dispose();
            }
        }

        public void InsertData<T>(T dataObject, string tableName = "")
        {
            if (tableName == "")
            {
                tableName = dataObject.GetType().Name;
            }

            using (IDbConnection connection = GetDbConnection())
            {
                connection.Open();

                using (IDbCommand command = GetDbCommand())
                {
                    command.Connection = connection;
                    command.CommandText = BuildSqlInsertStatement(dataObject, tableName);

                    command.ExecuteNonQuery();

                    command.Dispose();
                }

                connection.Close();
                connection.Dispose();
            }
        }

        protected DataTable ReadData<T>(string sqlStatement)
        {
            DataTable dataTable;

            using (IDbConnection connection = GetDbConnection())
            {
                connection.Open();

                using (IDbCommand command = GetDbCommand())
                {
                    command.Connection = connection;

                    dataTable = MappingHelper.CreateTypedDataTable<T>();
                    command.CommandText = sqlStatement;

                    IDataReader reader = command.ExecuteReader();
                    dataTable.Load(reader);

                    command.Dispose();
                }

                connection.Close();
                connection.Dispose();
            }

            return dataTable;
        }

        protected string BuildSqlInsertStatement<T>(T dataObject, string tableName)
        {
            string columnNames = string.Empty;
            string valueList = string.Empty;

            Type type = typeof (T);
            PropertyInfo[] properties = type.GetProperties();

            foreach (PropertyInfo propertyInfo in properties)
            {
                if (IsPrimaryKey(propertyInfo))
                {
                    if (!IsPrimaryKeyAutogenerated(propertyInfo))
                    {
                        AddToColumnNamesAndValueList(dataObject, ref columnNames, propertyInfo, ref valueList);
                    }
                }
                else
                {
                    AddToColumnNamesAndValueList(dataObject, ref columnNames, propertyInfo, ref valueList);
                }
            }

            columnNames = columnNames.Substring(0, columnNames.Length - 2);
            valueList = valueList.Substring(0, valueList.Length - 2);

            return string.Format(SqlInsertTemplate, tableName, columnNames, valueList);
        }

        private bool IsPrimaryKeyAutogenerated(PropertyInfo propertyInfo)
        {
            if (Attribute.IsDefined(propertyInfo, typeof (PrimaryKeyAutogeneratedByDatabase)))
            {
                var autoGenerated =
                    (PrimaryKeyAutogeneratedByDatabase)
                        Attribute.GetCustomAttribute(propertyInfo, typeof (PrimaryKeyAutogeneratedByDatabase));

                return autoGenerated.IsAutogenerated;
            }

            return true;
        }

        private bool IsPrimaryKey(PropertyInfo propertyInfo)
        {
            return Attribute.IsDefined(propertyInfo, typeof (PrimaryKey));
        }

        private void AddToColumnNamesAndValueList<T>(T dataObject, ref string columnNames,
            PropertyInfo propertyInfo,
            ref string valueList)
        {
            columnNames += propertyInfo.Name;
            columnNames += " ,";

            valueList += Escape(propertyInfo.GetValue(dataObject));
            valueList += " ,";
        }

        private IDbConnection GetDbConnection()
        {
            switch (DatabaseType)
            {
                case Database.MsSql:
                    return new SqlConnection(ConnectionString);
                case Database.MySql:
                    return new MySqlConnection(ConnectionString);
                case Database.Sqlite:
                    return new SQLiteConnection(ConnectionString);
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        private IDbCommand GetDbCommand()
        {
            switch (DatabaseType)
            {
                case Database.MsSql:
                    return new SqlCommand();
                case Database.MySql:
                    return new MySqlCommand();
                case Database.Sqlite:
                    return new SQLiteCommand();
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        protected abstract string Escape(object dataValue);
    }
}